[2022-07-05 05:31:02,563] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 05:31:02,670] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 05:31:02,670] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:31:02,671] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:31:02,671] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:31:02,787] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 02:00:00+00:00
[2022-07-05 05:31:02,809] {standard_task_runner.py:52} INFO - Started process 614 to run task
[2022-07-05 05:31:02,849] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T02:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpa5hbg30w', '--error-file', '/tmp/tmppxtxi6bl']
[2022-07-05 05:31:02,853] {standard_task_runner.py:77} INFO - Job 141: Subtask kimuksung_test
[2022-07-05 05:31:03,150] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:31:03,439] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T02:00:00+00:00
[2022-07-05 05:31:03,440] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:31:03,442] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:31:03,523] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T020000, start_date=20220705T053102, end_date=20220705T053103
[2022-07-05 05:31:03,618] {standard_task_runner.py:92} ERROR - Failed to execute job 141 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:31:03,707] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:31:04,089] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:21:01,564] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 07:21:01,608] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 07:21:01,608] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:01,608] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:01,608] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:01,696] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 02:00:00+00:00
[2022-07-05 07:21:01,716] {standard_task_runner.py:52} INFO - Started process 538 to run task
[2022-07-05 07:21:01,728] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T02:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpzbtz0hbf', '--error-file', '/tmp/tmpr6dkhsla']
[2022-07-05 07:21:01,735] {standard_task_runner.py:77} INFO - Job 231: Subtask kimuksung_test
[2022-07-05 07:21:02,334] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:02,880] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T02:00:00+00:00
[2022-07-05 07:21:02,882] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:02,882] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:02,916] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T020000, start_date=20220705T072101, end_date=20220705T072102
[2022-07-05 07:21:02,948] {standard_task_runner.py:92} ERROR - Failed to execute job 231 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:03,000] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:03,064] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:11,375] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 07:25:11,616] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 07:25:11,616] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:11,616] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:11,617] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:11,752] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 02:00:00+00:00
[2022-07-05 07:25:11,780] {standard_task_runner.py:52} INFO - Started process 728 to run task
[2022-07-05 07:25:11,802] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T02:00:00+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp8d2l6ypz', '--error-file', '/tmp/tmpjnqq9cbi']
[2022-07-05 07:25:11,803] {standard_task_runner.py:77} INFO - Job 262: Subtask kimuksung_test
[2022-07-05 07:25:12,272] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:12,570] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T02:00:00+00:00
[2022-07-05 07:25:12,572] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:12,572] {test.py:22} INFO - pubg
[2022-07-05 07:25:12,572] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:12,664] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T020000, start_date=20220705T072511, end_date=20220705T072512
[2022-07-05 07:25:12,795] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:12,896] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:28,722] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 08:05:28,796] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 08:05:28,796] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:28,796] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:28,796] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:28,991] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 02:00:00+00:00
[2022-07-05 08:05:29,055] {standard_task_runner.py:52} INFO - Started process 2069 to run task
[2022-07-05 08:05:29,078] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T02:00:00+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6xbtjnl4', '--error-file', '/tmp/tmpi3yg_8il']
[2022-07-05 08:05:29,078] {standard_task_runner.py:77} INFO - Job 295: Subtask kimuksung_test
[2022-07-05 08:05:29,399] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:29,752] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T02:00:00+00:00
[2022-07-05 08:05:29,755] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:29,755] {test.py:22} INFO - pubg
[2022-07-05 08:05:29,755] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:29,969] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T020000, start_date=20220705T080528, end_date=20220705T080529
[2022-07-05 08:05:30,095] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:05:30,371] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:10:42,917] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 08:10:43,060] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [queued]>
[2022-07-05 08:10:43,061] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:43,061] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:10:43,061] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:43,174] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 02:00:00+00:00
[2022-07-05 08:10:43,231] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T02:00:00+00:00', '--job-id', '358', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpa75sbhwy', '--error-file', '/tmp/tmpl20lb8dt']
[2022-07-05 08:10:43,231] {standard_task_runner.py:77} INFO - Job 358: Subtask kimuksung_test
[2022-07-05 08:10:43,203] {standard_task_runner.py:52} INFO - Started process 2365 to run task
[2022-07-05 08:10:43,616] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T02:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:10:43,968] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T02:00:00+00:00
[2022-07-05 08:10:43,970] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:10:43,970] {test.py:22} INFO - pubg
[2022-07-05 08:10:43,971] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:10:44,105] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T020000, start_date=20220705T081042, end_date=20220705T081044
[2022-07-05 08:10:44,229] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:10:44,358] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
