[2022-07-05 05:32:32,537] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 05:32:32,604] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 05:32:32,605] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:32:32,613] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:32:32,613] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:32:32,703] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 07:00:00+00:00
[2022-07-05 05:32:32,710] {standard_task_runner.py:52} INFO - Started process 718 to run task
[2022-07-05 05:32:32,758] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T07:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp9gqgjrot', '--error-file', '/tmp/tmp1mley3u1']
[2022-07-05 05:32:32,759] {standard_task_runner.py:77} INFO - Job 171: Subtask kimuksung_test
[2022-07-05 05:32:33,155] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:32:33,638] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T07:00:00+00:00
[2022-07-05 05:32:33,639] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:32:33,639] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:32:33,748] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T070000, start_date=20220705T053232, end_date=20220705T053233
[2022-07-05 05:32:33,867] {standard_task_runner.py:92} ERROR - Failed to execute job 171 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:32:33,937] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:32:34,426] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:21:07,987] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 07:21:08,129] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 07:21:08,132] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:08,132] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:08,133] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:08,207] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 07:00:00+00:00
[2022-07-05 07:21:08,218] {standard_task_runner.py:52} INFO - Started process 547 to run task
[2022-07-05 07:21:08,237] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T07:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpsketsbj5', '--error-file', '/tmp/tmp6vjcxq7f']
[2022-07-05 07:21:08,239] {standard_task_runner.py:77} INFO - Job 236: Subtask kimuksung_test
[2022-07-05 07:21:08,528] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:08,871] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T07:00:00+00:00
[2022-07-05 07:21:08,872] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:08,872] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:08,987] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T070000, start_date=20220705T072107, end_date=20220705T072108
[2022-07-05 07:21:09,069] {standard_task_runner.py:92} ERROR - Failed to execute job 236 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:09,102] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:09,283] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:19,005] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 07:25:19,062] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 07:25:19,062] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:19,062] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:19,062] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:19,126] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 07:00:00+00:00
[2022-07-05 07:25:19,146] {standard_task_runner.py:52} INFO - Started process 738 to run task
[2022-07-05 07:25:19,177] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T07:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpaq8hx1pt', '--error-file', '/tmp/tmpxkx5qafl']
[2022-07-05 07:25:19,178] {standard_task_runner.py:77} INFO - Job 267: Subtask kimuksung_test
[2022-07-05 07:25:19,478] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:19,696] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T07:00:00+00:00
[2022-07-05 07:25:19,700] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:19,700] {test.py:22} INFO - pubg
[2022-07-05 07:25:19,701] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:19,760] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T070000, start_date=20220705T072519, end_date=20220705T072519
[2022-07-05 07:25:19,811] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:19,887] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:41,633] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 08:05:41,673] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 08:05:41,674] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:41,674] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:41,674] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:41,738] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 07:00:00+00:00
[2022-07-05 08:05:41,751] {standard_task_runner.py:52} INFO - Started process 2088 to run task
[2022-07-05 08:05:41,758] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T07:00:00+00:00', '--job-id', '306', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpkehda4z6', '--error-file', '/tmp/tmpbotwku8o']
[2022-07-05 08:05:41,759] {standard_task_runner.py:77} INFO - Job 306: Subtask kimuksung_test
[2022-07-05 08:05:41,901] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:42,088] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T07:00:00+00:00
[2022-07-05 08:05:42,090] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:42,090] {test.py:22} INFO - pubg
[2022-07-05 08:05:42,090] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:42,142] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T070000, start_date=20220705T080541, end_date=20220705T080542
[2022-07-05 08:05:42,217] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:05:42,299] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:10:56,256] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 08:10:56,300] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [queued]>
[2022-07-05 08:10:56,301] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:56,302] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:10:56,302] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:56,371] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 07:00:00+00:00
[2022-07-05 08:10:56,390] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T07:00:00+00:00', '--job-id', '369', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp1kh2ec6r', '--error-file', '/tmp/tmpvfp_46pr']
[2022-07-05 08:10:56,391] {standard_task_runner.py:77} INFO - Job 369: Subtask kimuksung_test
[2022-07-05 08:10:56,378] {standard_task_runner.py:52} INFO - Started process 2388 to run task
[2022-07-05 08:10:56,688] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T07:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:10:57,063] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T07:00:00+00:00
[2022-07-05 08:10:57,066] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:10:57,067] {test.py:22} INFO - pubg
[2022-07-05 08:10:57,067] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:10:57,241] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T070000, start_date=20220705T081056, end_date=20220705T081057
[2022-07-05 08:10:57,372] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:10:57,481] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
