[2022-07-05 05:34:01,918] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 05:34:01,972] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 05:34:01,972] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:34:01,973] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:34:01,973] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:34:02,069] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 13:00:00+00:00
[2022-07-05 05:34:02,079] {standard_task_runner.py:52} INFO - Started process 827 to run task
[2022-07-05 05:34:02,082] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T13:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpc495_w8n', '--error-file', '/tmp/tmp4ak44kty']
[2022-07-05 05:34:02,105] {standard_task_runner.py:77} INFO - Job 207: Subtask kimuksung_test
[2022-07-05 05:34:02,336] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:34:02,723] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T13:00:00+00:00
[2022-07-05 05:34:02,734] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:34:02,735] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:34:02,796] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T130000, start_date=20220705T053401, end_date=20220705T053402
[2022-07-05 05:34:02,861] {standard_task_runner.py:92} ERROR - Failed to execute job 207 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:34:02,923] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:34:03,160] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:21:18,274] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 07:21:18,324] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 07:21:18,324] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:18,324] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:18,324] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:18,397] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 13:00:00+00:00
[2022-07-05 07:21:18,405] {standard_task_runner.py:52} INFO - Started process 568 to run task
[2022-07-05 07:21:18,429] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T13:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpv4blwova', '--error-file', '/tmp/tmp30fci23h']
[2022-07-05 07:21:18,431] {standard_task_runner.py:77} INFO - Job 242: Subtask kimuksung_test
[2022-07-05 07:21:18,775] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:19,050] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T13:00:00+00:00
[2022-07-05 07:21:19,076] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:19,080] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:19,152] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T130000, start_date=20220705T072118, end_date=20220705T072119
[2022-07-05 07:21:19,241] {standard_task_runner.py:92} ERROR - Failed to execute job 242 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:19,301] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:19,412] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:30,648] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 07:25:30,718] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 07:25:30,718] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:30,721] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:30,721] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:30,810] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 13:00:00+00:00
[2022-07-05 07:25:30,817] {standard_task_runner.py:52} INFO - Started process 760 to run task
[2022-07-05 07:25:30,855] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T13:00:00+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpl251ld5f', '--error-file', '/tmp/tmpjq3xgcn0']
[2022-07-05 07:25:30,856] {standard_task_runner.py:77} INFO - Job 273: Subtask kimuksung_test
[2022-07-05 07:25:31,434] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:31,998] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T13:00:00+00:00
[2022-07-05 07:25:31,999] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:31,999] {test.py:22} INFO - pubg
[2022-07-05 07:25:31,999] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:32,254] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T130000, start_date=20220705T072530, end_date=20220705T072532
[2022-07-05 07:25:32,550] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:33,154] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:56,770] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 08:05:56,880] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 08:05:56,881] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:56,886] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:56,887] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:56,991] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 13:00:00+00:00
[2022-07-05 08:05:57,040] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T13:00:00+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmphembgr52', '--error-file', '/tmp/tmpwq24myyc']
[2022-07-05 08:05:57,041] {standard_task_runner.py:77} INFO - Job 317: Subtask kimuksung_test
[2022-07-05 08:05:57,017] {standard_task_runner.py:52} INFO - Started process 2120 to run task
[2022-07-05 08:05:57,535] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:58,129] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T13:00:00+00:00
[2022-07-05 08:05:58,130] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:58,130] {test.py:22} INFO - pubg
[2022-07-05 08:05:58,131] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:58,217] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T130000, start_date=20220705T080556, end_date=20220705T080558
[2022-07-05 08:05:58,332] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:05:58,611] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:11:08,614] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 08:11:08,719] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [queued]>
[2022-07-05 08:11:08,719] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:08,719] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:11:08,719] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:08,812] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 13:00:00+00:00
[2022-07-05 08:11:08,823] {standard_task_runner.py:52} INFO - Started process 2423 to run task
[2022-07-05 08:11:08,838] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T13:00:00+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp73mng0qx', '--error-file', '/tmp/tmpy5boha46']
[2022-07-05 08:11:08,839] {standard_task_runner.py:77} INFO - Job 382: Subtask kimuksung_test
[2022-07-05 08:11:09,202] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T13:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:11:09,524] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T13:00:00+00:00
[2022-07-05 08:11:09,530] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:11:09,530] {test.py:22} INFO - pubg
[2022-07-05 08:11:09,532] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:11:09,703] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T130000, start_date=20220705T081108, end_date=20220705T081109
[2022-07-05 08:11:09,844] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:11:10,213] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
