[2022-07-05 05:31:49,488] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 05:31:49,667] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 05:31:49,668] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:31:49,668] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:31:49,668] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:31:49,894] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 05:00:00+00:00
[2022-07-05 05:31:49,929] {standard_task_runner.py:52} INFO - Started process 677 to run task
[2022-07-05 05:31:49,988] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T05:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpka92n2f3', '--error-file', '/tmp/tmp649ejm0k']
[2022-07-05 05:31:49,988] {standard_task_runner.py:77} INFO - Job 159: Subtask kimuksung_test
[2022-07-05 05:31:50,941] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:31:51,437] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T05:00:00+00:00
[2022-07-05 05:31:51,439] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:31:51,439] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:31:51,501] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T050000, start_date=20220705T053149, end_date=20220705T053151
[2022-07-05 05:31:51,710] {standard_task_runner.py:92} ERROR - Failed to execute job 159 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:31:51,767] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:31:52,392] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:21:05,783] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 07:21:05,825] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 07:21:05,825] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:05,825] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:05,825] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:05,877] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 05:00:00+00:00
[2022-07-05 07:21:05,896] {standard_task_runner.py:52} INFO - Started process 543 to run task
[2022-07-05 07:21:05,917] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T05:00:00+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpwivayy3n', '--error-file', '/tmp/tmpuag0m6fl']
[2022-07-05 07:21:05,918] {standard_task_runner.py:77} INFO - Job 234: Subtask kimuksung_test
[2022-07-05 07:21:06,428] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:06,774] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T05:00:00+00:00
[2022-07-05 07:21:06,779] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:06,779] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:06,817] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T050000, start_date=20220705T072105, end_date=20220705T072106
[2022-07-05 07:21:06,870] {standard_task_runner.py:92} ERROR - Failed to execute job 234 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:06,930] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:07,057] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:16,745] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 07:25:16,777] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 07:25:16,777] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:16,777] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:16,778] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:16,841] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 05:00:00+00:00
[2022-07-05 07:25:16,867] {standard_task_runner.py:52} INFO - Started process 734 to run task
[2022-07-05 07:25:16,893] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T05:00:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpgsh5f9fd', '--error-file', '/tmp/tmpk0uwk906']
[2022-07-05 07:25:16,894] {standard_task_runner.py:77} INFO - Job 265: Subtask kimuksung_test
[2022-07-05 07:25:17,333] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:17,798] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T05:00:00+00:00
[2022-07-05 07:25:17,800] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:17,800] {test.py:22} INFO - pubg
[2022-07-05 07:25:17,801] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:17,920] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T050000, start_date=20220705T072516, end_date=20220705T072517
[2022-07-05 07:25:18,113] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:18,315] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:32,504] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 08:05:32,753] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 08:05:32,753] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:32,753] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:32,753] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:33,092] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 05:00:00+00:00
[2022-07-05 08:05:33,123] {standard_task_runner.py:52} INFO - Started process 2080 to run task
[2022-07-05 08:05:33,334] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T05:00:00+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpoa347u0v', '--error-file', '/tmp/tmpj0arp9tw']
[2022-07-05 08:05:33,335] {standard_task_runner.py:77} INFO - Job 300: Subtask kimuksung_test
[2022-07-05 08:05:34,715] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:35,478] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T05:00:00+00:00
[2022-07-05 08:05:35,481] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:35,489] {test.py:22} INFO - pubg
[2022-07-05 08:05:35,490] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:35,618] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T050000, start_date=20220705T080532, end_date=20220705T080535
[2022-07-05 08:05:35,753] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:05:35,982] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:10:47,039] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 08:10:47,206] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [queued]>
[2022-07-05 08:10:47,207] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:47,207] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:10:47,207] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:47,315] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 05:00:00+00:00
[2022-07-05 08:10:47,322] {standard_task_runner.py:52} INFO - Started process 2378 to run task
[2022-07-05 08:10:47,330] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T05:00:00+00:00', '--job-id', '364', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp8b9t1wf2', '--error-file', '/tmp/tmpscdxmjye']
[2022-07-05 08:10:47,363] {standard_task_runner.py:77} INFO - Job 364: Subtask kimuksung_test
[2022-07-05 08:10:47,717] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T05:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:10:47,900] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T05:00:00+00:00
[2022-07-05 08:10:47,901] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:10:47,902] {test.py:22} INFO - pubg
[2022-07-05 08:10:47,902] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:10:48,021] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T050000, start_date=20220705T081047, end_date=20220705T081048
[2022-07-05 08:10:48,093] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:10:48,259] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
