[2022-07-05 05:32:49,026] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 05:32:49,146] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 05:32:49,146] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:32:49,146] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:32:49,147] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:32:49,292] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 08:00:00+00:00
[2022-07-05 05:32:49,310] {standard_task_runner.py:52} INFO - Started process 739 to run task
[2022-07-05 05:32:49,329] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T08:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp3h0_lix_', '--error-file', '/tmp/tmp9esqnrf9']
[2022-07-05 05:32:49,342] {standard_task_runner.py:77} INFO - Job 177: Subtask kimuksung_test
[2022-07-05 05:32:49,836] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:32:50,277] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T08:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T08:00:00+00:00
[2022-07-05 05:32:50,278] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:32:50,279] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:32:50,328] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T080000, start_date=20220705T053249, end_date=20220705T053250
[2022-07-05 05:32:50,379] {standard_task_runner.py:92} ERROR - Failed to execute job 177 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:32:50,410] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:32:50,548] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:21:11,270] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 07:21:11,317] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 07:21:11,318] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:11,318] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:11,319] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:11,410] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 08:00:00+00:00
[2022-07-05 07:21:11,445] {standard_task_runner.py:52} INFO - Started process 550 to run task
[2022-07-05 07:21:11,464] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T08:00:00+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpmlqqonrv', '--error-file', '/tmp/tmpq32jdn9i']
[2022-07-05 07:21:11,465] {standard_task_runner.py:77} INFO - Job 237: Subtask kimuksung_test
[2022-07-05 07:21:11,852] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:12,090] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T08:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T08:00:00+00:00
[2022-07-05 07:21:12,091] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:12,091] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:12,162] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T080000, start_date=20220705T072111, end_date=20220705T072112
[2022-07-05 07:21:12,259] {standard_task_runner.py:92} ERROR - Failed to execute job 237 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:12,287] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:12,463] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:21,875] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 07:25:21,938] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 07:25:21,939] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:21,939] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:21,939] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:21,988] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 08:00:00+00:00
[2022-07-05 07:25:21,995] {standard_task_runner.py:52} INFO - Started process 740 to run task
[2022-07-05 07:25:22,004] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T08:00:00+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpurivdtb2', '--error-file', '/tmp/tmp2j5kfxs9']
[2022-07-05 07:25:22,005] {standard_task_runner.py:77} INFO - Job 268: Subtask kimuksung_test
[2022-07-05 07:25:22,464] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:22,952] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T08:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T08:00:00+00:00
[2022-07-05 07:25:22,954] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:22,955] {test.py:22} INFO - pubg
[2022-07-05 07:25:22,955] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:23,139] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T080000, start_date=20220705T072521, end_date=20220705T072523
[2022-07-05 07:25:23,311] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:23,538] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:45,350] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 08:05:45,559] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 08:05:45,559] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:45,562] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:45,562] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:45,683] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 08:00:00+00:00
[2022-07-05 08:05:45,706] {standard_task_runner.py:52} INFO - Started process 2100 to run task
[2022-07-05 08:05:45,743] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T08:00:00+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp7jsvy_gz', '--error-file', '/tmp/tmposbjun48']
[2022-07-05 08:05:45,744] {standard_task_runner.py:77} INFO - Job 307: Subtask kimuksung_test
[2022-07-05 08:05:46,283] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:46,704] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T08:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T08:00:00+00:00
[2022-07-05 08:05:46,710] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:46,710] {test.py:22} INFO - pubg
[2022-07-05 08:05:46,710] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:46,854] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T080000, start_date=20220705T080545, end_date=20220705T080546
[2022-07-05 08:05:47,043] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:05:47,690] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:10:56,966] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 08:10:57,002] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [queued]>
[2022-07-05 08:10:57,002] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:57,002] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:10:57,002] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:57,045] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 08:00:00+00:00
[2022-07-05 08:10:57,053] {standard_task_runner.py:52} INFO - Started process 2389 to run task
[2022-07-05 08:10:57,072] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T08:00:00+00:00', '--job-id', '370', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpiekm7y6d', '--error-file', '/tmp/tmpqeje24uv']
[2022-07-05 08:10:57,073] {standard_task_runner.py:77} INFO - Job 370: Subtask kimuksung_test
[2022-07-05 08:10:57,453] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T08:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:10:57,880] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T08:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T08:00:00+00:00
[2022-07-05 08:10:57,881] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:10:57,881] {test.py:22} INFO - pubg
[2022-07-05 08:10:57,881] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:10:58,005] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T080000, start_date=20220705T081056, end_date=20220705T081058
[2022-07-05 08:10:58,106] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:10:58,664] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
