[2022-07-05 05:22:57,814] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-03T01:41:00+00:00 [queued]>
[2022-07-05 05:22:57,883] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-03T01:41:00+00:00 [queued]>
[2022-07-05 05:22:57,883] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:22:57,883] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:22:57,883] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:22:57,956] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-03 01:41:00+00:00
[2022-07-05 05:22:57,962] {standard_task_runner.py:52} INFO - Started process 354 to run task
[2022-07-05 05:22:57,979] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-03T01:41:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpomdbr61k', '--error-file', '/tmp/tmp0s2pkrnf']
[2022-07-05 05:22:57,980] {standard_task_runner.py:77} INFO - Job 126: Subtask kimuksung_test
[2022-07-05 05:22:58,469] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-03T01:41:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:22:59,232] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-03T01:41:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-03T01:41:00+00:00
[2022-07-05 05:22:59,233] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:22:59,234] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:22:59,649] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220703T014100, start_date=20220705T052257, end_date=20220705T052259
[2022-07-05 05:22:59,901] {standard_task_runner.py:92} ERROR - Failed to execute job 126 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:23:00,031] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:23:00,621] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 05:23:00,821] {dagrun.py:530} ERROR - Marking run <DagRun uk_dag_test_1 @ 2022-07-03 01:41:00+00:00: scheduled__2022-07-03T01:41:00+00:00, externally triggered: False> failed
[2022-07-05 05:23:00,823] {dagrun.py:605} INFO - DagRun Finished: dag_id=uk_dag_test_1, execution_date=2022-07-03 01:41:00+00:00, run_id=scheduled__2022-07-03T01:41:00+00:00, run_start_date=2022-07-05 05:22:51.273551+00:00, run_end_date=2022-07-05 05:23:00.822755+00:00, run_duration=9.549204, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2022-07-03 01:41:00+00:00, data_interval_end=2022-07-03 01:42:00+00:00, dag_hash=e79e5dfaea90566f59ca7d34682eb16a
