[2022-07-05 05:32:59,675] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 05:32:59,741] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 05:32:59,741] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:32:59,741] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:32:59,741] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:32:59,824] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 09:00:00+00:00
[2022-07-05 05:32:59,851] {standard_task_runner.py:52} INFO - Started process 752 to run task
[2022-07-05 05:32:59,871] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T09:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpy0fk42s6', '--error-file', '/tmp/tmpnlruw2tf']
[2022-07-05 05:32:59,872] {standard_task_runner.py:77} INFO - Job 183: Subtask kimuksung_test
[2022-07-05 05:33:00,366] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:33:00,933] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T09:00:00+00:00
[2022-07-05 05:33:00,934] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:33:00,935] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:33:01,096] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T090000, start_date=20220705T053259, end_date=20220705T053301
[2022-07-05 05:33:01,200] {standard_task_runner.py:92} ERROR - Failed to execute job 183 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:33:01,244] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:33:01,488] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:21:11,927] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 07:21:11,977] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 07:21:11,980] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:11,980] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:11,980] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:12,027] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 09:00:00+00:00
[2022-07-05 07:21:12,040] {standard_task_runner.py:52} INFO - Started process 551 to run task
[2022-07-05 07:21:12,049] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T09:00:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp2tcipe0e', '--error-file', '/tmp/tmp_t06lr4d']
[2022-07-05 07:21:12,050] {standard_task_runner.py:77} INFO - Job 238: Subtask kimuksung_test
[2022-07-05 07:21:12,296] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:12,567] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T09:00:00+00:00
[2022-07-05 07:21:12,568] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:12,568] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:12,673] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T090000, start_date=20220705T072111, end_date=20220705T072112
[2022-07-05 07:21:12,764] {standard_task_runner.py:92} ERROR - Failed to execute job 238 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:12,812] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:12,979] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:23,009] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 07:25:23,076] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 07:25:23,076] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:23,076] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:23,076] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:23,177] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 09:00:00+00:00
[2022-07-05 07:25:23,203] {standard_task_runner.py:52} INFO - Started process 742 to run task
[2022-07-05 07:25:23,243] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T09:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpx73fxpeb', '--error-file', '/tmp/tmp7glid_dw']
[2022-07-05 07:25:23,243] {standard_task_runner.py:77} INFO - Job 269: Subtask kimuksung_test
[2022-07-05 07:25:23,850] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:24,201] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T09:00:00+00:00
[2022-07-05 07:25:24,203] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:24,203] {test.py:22} INFO - pubg
[2022-07-05 07:25:24,203] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:24,466] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T090000, start_date=20220705T072523, end_date=20220705T072524
[2022-07-05 07:25:24,703] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:24,864] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:46,666] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 08:05:46,752] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 08:05:46,753] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:46,753] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:46,753] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:46,866] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 09:00:00+00:00
[2022-07-05 08:05:46,972] {standard_task_runner.py:52} INFO - Started process 2101 to run task
[2022-07-05 08:05:46,977] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T09:00:00+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6kp8elk6', '--error-file', '/tmp/tmp9al8xyqy']
[2022-07-05 08:05:46,978] {standard_task_runner.py:77} INFO - Job 309: Subtask kimuksung_test
[2022-07-05 08:05:47,561] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:48,060] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T09:00:00+00:00
[2022-07-05 08:05:48,065] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:48,065] {test.py:22} INFO - pubg
[2022-07-05 08:05:48,066] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:48,537] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T090000, start_date=20220705T080546, end_date=20220705T080548
[2022-07-05 08:05:48,689] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:05:48,866] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:10:58,626] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 08:10:58,708] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [queued]>
[2022-07-05 08:10:58,709] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:58,709] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:10:58,709] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:58,829] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 09:00:00+00:00
[2022-07-05 08:10:58,838] {standard_task_runner.py:52} INFO - Started process 2399 to run task
[2022-07-05 08:10:58,860] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T09:00:00+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpdwda5tmt', '--error-file', '/tmp/tmprfqt88m_']
[2022-07-05 08:10:58,869] {standard_task_runner.py:77} INFO - Job 371: Subtask kimuksung_test
[2022-07-05 08:10:59,475] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T09:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:11:00,170] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T09:00:00+00:00
[2022-07-05 08:11:00,173] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:11:00,173] {test.py:22} INFO - pubg
[2022-07-05 08:11:00,173] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:11:00,411] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T090000, start_date=20220705T081058, end_date=20220705T081100
[2022-07-05 08:11:00,614] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:11:00,961] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
