[2022-07-20 04:45:25,685] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 04:45:25,742] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 04:45:25,743] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:45:25,743] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-20 04:45:25,743] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:45:25,840] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-07-19 00:00:00+00:00
[2022-07-20 04:45:25,891] {standard_task_runner.py:52} INFO - Started process 89 to run task
[2022-07-20 04:45:25,915] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_xcom_test', 'insert_into_table', 'scheduled__2022-07-19T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/postgres_xcom_test.py', '--cfg-path', '/tmp/tmpz2jds6bp', '--error-file', '/tmp/tmpo6zt7ro3']
[2022-07-20 04:45:25,915] {standard_task_runner.py:77} INFO - Job 72: Subtask insert_into_table
[2022-07-20 04:45:26,356] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-20 04:45:26,572] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=postgres_xcom_test
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T00:00:00+00:00
[2022-07-20 04:45:26,592] {base.py:79} INFO - Using connection to: id: postgres_xcom_test. Host: postgres, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-20 04:45:26,605] {dbapi.py:225} INFO - Running statement: 
            insert into test_data (char_list) values ('None')
        , parameters: None
[2022-07-20 04:45:26,613] {dbapi.py:233} INFO - Rows affected: 1
[2022-07-20 04:45:26,755] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=postgres_xcom_test, task_id=insert_into_table, execution_date=20220719T000000, start_date=20220720T044525, end_date=20220720T044526
[2022-07-20 04:45:26,876] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-20 04:45:27,140] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-20 04:47:00,217] {taskinstance.py:1031} INFO - Dependencies not met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'get_data'}
[2022-07-20 04:47:00,223] {local_task_job.py:99} INFO - Task is not able to be run
[2022-07-20 05:00:30,858] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 05:00:30,871] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 05:00:30,871] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 05:00:30,871] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-20 05:00:30,871] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 05:00:30,888] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-07-19 00:00:00+00:00
[2022-07-20 05:00:30,891] {standard_task_runner.py:52} INFO - Started process 631 to run task
[2022-07-20 05:00:30,895] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_xcom_test', 'insert_into_table', 'scheduled__2022-07-19T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/postgres_xcom_test.py', '--cfg-path', '/tmp/tmpjwgb9jtq', '--error-file', '/tmp/tmpagb17tgu']
[2022-07-20 05:00:30,895] {standard_task_runner.py:77} INFO - Job 80: Subtask insert_into_table
[2022-07-20 05:00:30,952] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-20 05:00:31,030] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=postgres_xcom_test
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T00:00:00+00:00
[2022-07-20 05:00:31,041] {base.py:79} INFO - Using connection to: id: postgres_xcom_test. Host: postgres, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-20 05:00:31,046] {dbapi.py:225} INFO - Running statement: 
            insert into test_data (char_list) values ('{'3': 5}')
        , parameters: None
[2022-07-20 05:00:31,047] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "3"
LINE 2: ...       insert into test_data (char_list) values ('{'3': 5}')
                                                               ^

[2022-07-20 05:00:31,069] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_xcom_test, task_id=insert_into_table, execution_date=20220719T000000, start_date=20220720T050030, end_date=20220720T050031
[2022-07-20 05:00:31,088] {standard_task_runner.py:92} ERROR - Failed to execute job 80 for task insert_into_table
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "3"
LINE 2: ...       insert into test_data (char_list) values ('{'3': 5}')
                                                               ^

[2022-07-20 05:00:31,107] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-20 05:00:31,146] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-20 05:04:14,852] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 05:04:14,868] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 05:04:14,868] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 05:04:14,868] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-20 05:04:14,868] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 05:04:14,885] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-07-19 00:00:00+00:00
[2022-07-20 05:04:14,890] {standard_task_runner.py:52} INFO - Started process 775 to run task
[2022-07-20 05:04:14,894] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_xcom_test', 'insert_into_table', 'scheduled__2022-07-19T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/postgres_xcom_test.py', '--cfg-path', '/tmp/tmpmws7u7vg', '--error-file', '/tmp/tmpkn_v3nmd']
[2022-07-20 05:04:14,894] {standard_task_runner.py:77} INFO - Job 83: Subtask insert_into_table
[2022-07-20 05:04:14,958] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-20 05:04:15,053] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=postgres_xcom_test
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T00:00:00+00:00
[2022-07-20 05:04:15,077] {base.py:79} INFO - Using connection to: id: postgres_xcom_test. Host: postgres, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-20 05:04:15,082] {dbapi.py:225} INFO - Running statement: 
            insert into test_data (char_list) values (5)
        , parameters: None
[2022-07-20 05:04:15,083] {dbapi.py:233} INFO - Rows affected: 1
[2022-07-20 05:04:15,108] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=postgres_xcom_test, task_id=insert_into_table, execution_date=20220719T000000, start_date=20220720T050414, end_date=20220720T050415
[2022-07-20 05:04:15,147] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-20 05:04:15,203] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
