[2022-07-20 04:52:02,445] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 04:52:02,465] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 04:52:02,467] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:52:02,467] {taskinstance.py:1244} INFO - Starting attempt 2 of 6
[2022-07-20 04:52:02,467] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:52:02,507] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-07-19 00:00:00+00:00
[2022-07-20 04:52:02,513] {standard_task_runner.py:52} INFO - Started process 343 to run task
[2022-07-20 04:52:02,521] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_xcom_test', 'insert_into_table', 'scheduled__2022-07-19T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/postgres_xcom_test.py', '--cfg-path', '/tmp/tmpwu7wzt4p', '--error-file', '/tmp/tmppjj0ex6q']
[2022-07-20 04:52:02,522] {standard_task_runner.py:77} INFO - Job 77: Subtask insert_into_table
[2022-07-20 04:52:02,618] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-20 04:52:02,729] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=postgres_xcom_test
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T00:00:00+00:00
[2022-07-20 04:52:02,742] {base.py:79} INFO - Using connection to: id: postgres_xcom_test. Host: postgres, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-20 04:52:02,747] {dbapi.py:225} INFO - Running statement: 
            insert into test_data (char_list) values ('None')
        , parameters: None
[2022-07-20 04:52:02,748] {dbapi.py:233} INFO - Rows affected: 1
[2022-07-20 04:52:02,777] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=postgres_xcom_test, task_id=insert_into_table, execution_date=20220719T000000, start_date=20220720T045202, end_date=20220720T045202
[2022-07-20 04:52:02,815] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-20 04:52:02,863] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-20 06:03:11,138] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 06:03:11,155] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 06:03:11,156] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 06:03:11,156] {taskinstance.py:1244} INFO - Starting attempt 2 of 7
[2022-07-20 06:03:11,156] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 06:03:11,174] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-07-19 00:00:00+00:00
[2022-07-20 06:03:11,179] {standard_task_runner.py:52} INFO - Started process 1200 to run task
[2022-07-20 06:03:11,184] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_xcom_test', 'insert_into_table', 'scheduled__2022-07-19T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/postgres_xcom_test.py', '--cfg-path', '/tmp/tmp_c_kd_vm', '--error-file', '/tmp/tmp3302ydub']
[2022-07-20 06:03:11,185] {standard_task_runner.py:77} INFO - Job 106: Subtask insert_into_table
[2022-07-20 06:03:11,270] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-20 06:03:11,367] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=postgres_xcom_test
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T00:00:00+00:00
[2022-07-20 06:03:11,379] {base.py:79} INFO - Using connection to: id: postgres_xcom_test. Host: postgres, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-20 06:03:11,384] {dbapi.py:225} INFO - Running statement: 
            insert into test_data (char_list) values (2022-07-18T23:59:00)
        , parameters: None
[2022-07-20 06:03:11,386] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "T23"
LINE 2: ...sert into test_data (char_list) values (2022-07-18T23:59:00)
                                                             ^

[2022-07-20 06:03:11,403] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_xcom_test, task_id=insert_into_table, execution_date=20220719T000000, start_date=20220720T060311, end_date=20220720T060311
[2022-07-20 06:03:11,424] {standard_task_runner.py:92} ERROR - Failed to execute job 106 for task insert_into_table
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "T23"
LINE 2: ...sert into test_data (char_list) values (2022-07-18T23:59:00)
                                                             ^

[2022-07-20 06:03:11,436] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-20 06:03:11,475] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
