[2022-07-20 06:14:55,978] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 06:14:55,990] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 06:14:55,990] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 06:14:55,990] {taskinstance.py:1244} INFO - Starting attempt 7 of 12
[2022-07-20 06:14:55,990] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 06:14:56,005] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-07-19 00:00:00+00:00
[2022-07-20 06:14:56,011] {standard_task_runner.py:52} INFO - Started process 1567 to run task
[2022-07-20 06:14:56,018] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_xcom_test', 'insert_into_table', 'scheduled__2022-07-19T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/postgres_xcom_test.py', '--cfg-path', '/tmp/tmpkx_j5g3z', '--error-file', '/tmp/tmp86qv4u4x']
[2022-07-20 06:14:56,019] {standard_task_runner.py:77} INFO - Job 121: Subtask insert_into_table
[2022-07-20 06:14:56,089] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_xcom_test.insert_into_table scheduled__2022-07-19T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-20 06:14:56,179] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kimuksung2
AIRFLOW_CTX_DAG_ID=postgres_xcom_test
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T00:00:00+00:00
[2022-07-20 06:14:56,191] {base.py:79} INFO - Using connection to: id: postgres_xcom_test. Host: postgres, Port: 5432, Schema: test, Login: ***, Password: ***, extra: {}
[2022-07-20 06:14:56,195] {dbapi.py:225} INFO - Running statement: 
            insert into test_data (dt) values (2022-07-18 23:59:00)
        , parameters: None
[2022-07-20 06:14:56,195] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "23"
LINE 2: ...     insert into test_data (dt) values (2022-07-18 23:59:00)
                                                              ^

[2022-07-20 06:14:56,210] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_xcom_test, task_id=insert_into_table, execution_date=20220719T000000, start_date=20220720T061455, end_date=20220720T061456
[2022-07-20 06:14:56,228] {standard_task_runner.py:92} ERROR - Failed to execute job 121 for task insert_into_table
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "23"
LINE 2: ...     insert into test_data (dt) values (2022-07-18 23:59:00)
                                                              ^

[2022-07-20 06:14:56,270] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-20 06:14:56,317] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
