[2022-07-05 05:30:33,999] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 05:30:34,138] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 05:30:34,138] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:30:34,139] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:30:34,151] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:30:34,346] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 00:00:00+00:00
[2022-07-05 05:30:34,450] {standard_task_runner.py:52} INFO - Started process 583 to run task
[2022-07-05 05:30:34,477] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpcjll0uxi', '--error-file', '/tmp/tmppyri276d']
[2022-07-05 05:30:34,478] {standard_task_runner.py:77} INFO - Job 129: Subtask kimuksung_test
[2022-07-05 05:30:35,468] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:30:36,709] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T00:00:00+00:00
[2022-07-05 05:30:36,737] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:30:36,737] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:30:36,901] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T000000, start_date=20220705T053034, end_date=20220705T053036
[2022-07-05 05:30:37,111] {standard_task_runner.py:92} ERROR - Failed to execute job 129 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:30:37,202] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:30:37,841] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:20:58,864] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 07:20:58,928] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 07:20:58,928] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:20:58,928] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:20:58,928] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:20:59,053] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 00:00:00+00:00
[2022-07-05 07:20:59,068] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T00:00:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpwl1jktx9', '--error-file', '/tmp/tmpbq7sbfw4']
[2022-07-05 07:20:59,069] {standard_task_runner.py:77} INFO - Job 229: Subtask kimuksung_test
[2022-07-05 07:20:59,060] {standard_task_runner.py:52} INFO - Started process 533 to run task
[2022-07-05 07:20:59,399] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:20:59,678] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T00:00:00+00:00
[2022-07-05 07:20:59,684] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:20:59,685] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:20:59,781] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T000000, start_date=20220705T072058, end_date=20220705T072059
[2022-07-05 07:20:59,898] {standard_task_runner.py:92} ERROR - Failed to execute job 229 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:20:59,964] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:00,316] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:09,635] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 07:25:09,679] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 07:25:09,679] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:09,680] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:09,680] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:09,746] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 00:00:00+00:00
[2022-07-05 07:25:09,765] {standard_task_runner.py:52} INFO - Started process 725 to run task
[2022-07-05 07:25:09,779] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T00:00:00+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpd9j7f8hg', '--error-file', '/tmp/tmp_u81yt1q']
[2022-07-05 07:25:09,780] {standard_task_runner.py:77} INFO - Job 260: Subtask kimuksung_test
[2022-07-05 07:25:09,999] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:10,277] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T00:00:00+00:00
[2022-07-05 07:25:10,279] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:10,280] {test.py:22} INFO - pubg
[2022-07-05 07:25:10,280] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:10,489] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T000000, start_date=20220705T072509, end_date=20220705T072510
[2022-07-05 07:25:10,742] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:11,098] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:26,153] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 08:05:26,176] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 08:05:26,177] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:26,177] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:26,177] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:26,247] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 00:00:00+00:00
[2022-07-05 08:05:26,252] {standard_task_runner.py:52} INFO - Started process 2060 to run task
[2022-07-05 08:05:26,258] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T00:00:00+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmps13jzfid', '--error-file', '/tmp/tmpdv48wyjg']
[2022-07-05 08:05:26,259] {standard_task_runner.py:77} INFO - Job 292: Subtask kimuksung_test
[2022-07-05 08:05:26,470] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:26,637] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T00:00:00+00:00
[2022-07-05 08:05:26,638] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:26,639] {test.py:22} INFO - pubg
[2022-07-05 08:05:26,639] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:26,722] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T000000, start_date=20220705T080526, end_date=20220705T080526
[2022-07-05 08:05:26,806] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:05:26,999] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:10:40,883] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 08:10:40,937] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 08:10:40,938] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:40,938] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:10:40,938] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:41,022] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 00:00:00+00:00
[2022-07-05 08:10:41,028] {standard_task_runner.py:52} INFO - Started process 2362 to run task
[2022-07-05 08:10:41,048] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T00:00:00+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpgykjehan', '--error-file', '/tmp/tmpiawh_c01']
[2022-07-05 08:10:41,049] {standard_task_runner.py:77} INFO - Job 356: Subtask kimuksung_test
[2022-07-05 08:10:41,352] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T00:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:10:41,754] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T00:00:00+00:00
[2022-07-05 08:10:41,756] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:10:41,756] {test.py:22} INFO - pubg
[2022-07-05 08:10:41,756] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:10:41,895] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T000000, start_date=20220705T081040, end_date=20220705T081041
[2022-07-05 08:10:41,999] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:10:42,285] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
