[2022-07-11 06:29:16,170] {processor.py:163} INFO - Started process (PID=47) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:29:16,172] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:29:16,173] {logging_mixin.py:109} INFO - [2022-07-11 06:29:16,173] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:29:17,533] {logging_mixin.py:109} INFO - [2022-07-11 06:29:17,529] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:29:17,559] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:29:17,580] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 1.436 seconds
[2022-07-11 06:29:47,968] {processor.py:163} INFO - Started process (PID=73) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:29:47,971] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:29:47,972] {logging_mixin.py:109} INFO - [2022-07-11 06:29:47,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:29:48,557] {logging_mixin.py:109} INFO - [2022-07-11 06:29:48,555] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:29:48,579] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:29:48,601] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.640 seconds
[2022-07-11 06:30:18,634] {processor.py:163} INFO - Started process (PID=98) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:30:18,636] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:30:18,637] {logging_mixin.py:109} INFO - [2022-07-11 06:30:18,637] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:30:19,472] {logging_mixin.py:109} INFO - [2022-07-11 06:30:19,470] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:30:19,491] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:30:19,503] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.875 seconds
[2022-07-11 06:30:49,882] {processor.py:163} INFO - Started process (PID=122) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:30:49,884] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:30:49,886] {logging_mixin.py:109} INFO - [2022-07-11 06:30:49,885] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:30:50,385] {logging_mixin.py:109} INFO - [2022-07-11 06:30:50,382] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:30:50,409] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:30:50,425] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.552 seconds
[2022-07-11 06:31:21,288] {processor.py:163} INFO - Started process (PID=146) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:31:21,290] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:31:21,291] {logging_mixin.py:109} INFO - [2022-07-11 06:31:21,291] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:31:21,744] {logging_mixin.py:109} INFO - [2022-07-11 06:31:21,742] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:31:21,761] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:31:21,773] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.492 seconds
[2022-07-11 06:31:52,611] {processor.py:163} INFO - Started process (PID=171) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:31:52,617] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:31:52,620] {logging_mixin.py:109} INFO - [2022-07-11 06:31:52,619] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:31:53,169] {logging_mixin.py:109} INFO - [2022-07-11 06:31:53,167] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:31:53,183] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:31:53,194] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.594 seconds
[2022-07-11 06:32:23,961] {processor.py:163} INFO - Started process (PID=202) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:32:23,968] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:32:23,969] {logging_mixin.py:109} INFO - [2022-07-11 06:32:23,969] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:32:24,433] {logging_mixin.py:109} INFO - [2022-07-11 06:32:24,432] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:32:24,457] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:32:24,473] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.518 seconds
[2022-07-11 06:32:55,221] {processor.py:163} INFO - Started process (PID=227) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:32:55,223] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:32:55,224] {logging_mixin.py:109} INFO - [2022-07-11 06:32:55,224] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:32:55,774] {logging_mixin.py:109} INFO - [2022-07-11 06:32:55,772] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:32:55,796] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:32:55,811] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.597 seconds
[2022-07-11 06:33:26,749] {processor.py:163} INFO - Started process (PID=251) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:33:26,762] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:33:26,765] {logging_mixin.py:109} INFO - [2022-07-11 06:33:26,764] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:33:27,231] {logging_mixin.py:109} INFO - [2022-07-11 06:33:27,229] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:33:27,248] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:33:27,258] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.536 seconds
[2022-07-11 06:33:58,259] {processor.py:163} INFO - Started process (PID=276) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:33:58,267] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:33:58,273] {logging_mixin.py:109} INFO - [2022-07-11 06:33:58,272] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:33:58,818] {logging_mixin.py:109} INFO - [2022-07-11 06:33:58,816] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:33:58,837] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:33:58,849] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.607 seconds
[2022-07-11 06:34:29,847] {processor.py:163} INFO - Started process (PID=300) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:34:29,852] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:34:29,854] {logging_mixin.py:109} INFO - [2022-07-11 06:34:29,853] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:34:30,655] {logging_mixin.py:109} INFO - [2022-07-11 06:34:30,652] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:34:30,683] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:34:30,701] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.867 seconds
[2022-07-11 06:35:00,998] {processor.py:163} INFO - Started process (PID=324) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:35:01,002] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:35:01,004] {logging_mixin.py:109} INFO - [2022-07-11 06:35:01,004] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:35:01,593] {logging_mixin.py:109} INFO - [2022-07-11 06:35:01,591] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:35:01,617] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:35:01,636] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.650 seconds
[2022-07-11 06:35:32,427] {processor.py:163} INFO - Started process (PID=348) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:35:32,432] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:35:32,434] {logging_mixin.py:109} INFO - [2022-07-11 06:35:32,434] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:35:32,889] {logging_mixin.py:109} INFO - [2022-07-11 06:35:32,887] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:35:32,916] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:35:32,930] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.519 seconds
[2022-07-11 06:36:03,825] {processor.py:163} INFO - Started process (PID=381) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:36:03,826] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:36:03,827] {logging_mixin.py:109} INFO - [2022-07-11 06:36:03,827] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:36:04,249] {logging_mixin.py:109} INFO - [2022-07-11 06:36:04,247] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:36:04,267] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:36:04,279] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.459 seconds
[2022-07-11 06:36:35,256] {processor.py:163} INFO - Started process (PID=405) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:36:35,260] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:36:35,261] {logging_mixin.py:109} INFO - [2022-07-11 06:36:35,261] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:36:35,865] {logging_mixin.py:109} INFO - [2022-07-11 06:36:35,864] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:36:35,884] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:36:35,897] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.647 seconds
[2022-07-11 06:37:06,652] {processor.py:163} INFO - Started process (PID=429) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:37:06,656] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:37:06,658] {logging_mixin.py:109} INFO - [2022-07-11 06:37:06,658] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:37:07,162] {logging_mixin.py:109} INFO - [2022-07-11 06:37:07,161] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:37:07,179] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:37:07,190] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.550 seconds
[2022-07-11 06:37:37,917] {processor.py:163} INFO - Started process (PID=453) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:37:37,939] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:37:37,952] {logging_mixin.py:109} INFO - [2022-07-11 06:37:37,951] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:37:38,515] {logging_mixin.py:109} INFO - [2022-07-11 06:37:38,514] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:37:38,530] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:37:38,542] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.646 seconds
[2022-07-11 06:38:09,443] {processor.py:163} INFO - Started process (PID=477) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:38:09,445] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:38:09,447] {logging_mixin.py:109} INFO - [2022-07-11 06:38:09,446] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:38:09,900] {logging_mixin.py:109} INFO - [2022-07-11 06:38:09,899] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:38:09,917] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:38:09,948] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.512 seconds
[2022-07-11 06:38:39,995] {processor.py:163} INFO - Started process (PID=502) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:38:39,999] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:38:40,001] {logging_mixin.py:109} INFO - [2022-07-11 06:38:40,000] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:38:40,685] {logging_mixin.py:109} INFO - [2022-07-11 06:38:40,683] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:38:40,718] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:38:40,735] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.752 seconds
[2022-07-11 06:39:11,487] {processor.py:163} INFO - Started process (PID=527) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:39:11,494] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:39:11,496] {logging_mixin.py:109} INFO - [2022-07-11 06:39:11,496] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:39:12,015] {logging_mixin.py:109} INFO - [2022-07-11 06:39:12,009] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:39:12,053] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:39:12,073] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.615 seconds
[2022-07-11 06:39:42,978] {processor.py:163} INFO - Started process (PID=560) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:39:42,979] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:39:42,980] {logging_mixin.py:109} INFO - [2022-07-11 06:39:42,980] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:39:43,506] {logging_mixin.py:109} INFO - [2022-07-11 06:39:43,504] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:39:43,530] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:39:43,542] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.569 seconds
[2022-07-11 06:40:14,304] {processor.py:163} INFO - Started process (PID=584) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:40:14,306] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:40:14,306] {logging_mixin.py:109} INFO - [2022-07-11 06:40:14,306] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:40:14,691] {logging_mixin.py:109} INFO - [2022-07-11 06:40:14,690] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:40:14,742] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:40:14,757] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.457 seconds
[2022-07-11 06:40:45,666] {processor.py:163} INFO - Started process (PID=607) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:40:45,667] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:40:45,667] {logging_mixin.py:109} INFO - [2022-07-11 06:40:45,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:40:46,065] {logging_mixin.py:109} INFO - [2022-07-11 06:40:46,063] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:40:46,082] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:40:46,093] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.431 seconds
[2022-07-11 06:41:17,066] {processor.py:163} INFO - Started process (PID=630) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:41:17,069] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:41:17,070] {logging_mixin.py:109} INFO - [2022-07-11 06:41:17,069] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:41:17,632] {logging_mixin.py:109} INFO - [2022-07-11 06:41:17,630] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:41:17,662] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:41:17,677] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.616 seconds
[2022-07-11 06:41:48,572] {processor.py:163} INFO - Started process (PID=654) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:41:48,573] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:41:48,574] {logging_mixin.py:109} INFO - [2022-07-11 06:41:48,574] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:41:49,206] {logging_mixin.py:109} INFO - [2022-07-11 06:41:49,203] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_postgres.py", line 10, in <module>
    start_date=datetime.datetime(2022, 7, 11),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-07-11 06:41:49,242] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:41:49,262] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.695 seconds
[2022-07-11 06:42:17,954] {processor.py:163} INFO - Started process (PID=679) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:42:17,962] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:42:17,964] {logging_mixin.py:109} INFO - [2022-07-11 06:42:17,963] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:42:18,628] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_operator_dag']) retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:42:23,343] {logging_mixin.py:109} INFO - [2022-07-11 06:42:23,342] {manager.py:496} INFO - Created Permission View: can read on DAG:postgres_operator_dag
[2022-07-11 06:42:23,360] {logging_mixin.py:109} INFO - [2022-07-11 06:42:23,360] {manager.py:496} INFO - Created Permission View: can edit on DAG:postgres_operator_dag
[2022-07-11 06:42:23,361] {logging_mixin.py:109} INFO - [2022-07-11 06:42:23,360] {dag.py:2398} INFO - Sync 1 DAGs
[2022-07-11 06:42:23,373] {logging_mixin.py:109} INFO - [2022-07-11 06:42:23,372] {dag.py:2417} INFO - Creating ORM DAG for postgres_operator_dag
[2022-07-11 06:42:23,384] {logging_mixin.py:109} INFO - [2022-07-11 06:42:23,384] {dag.py:2937} INFO - Setting next_dagrun for postgres_operator_dag to 2022-07-11T00:00:00+00:00
[2022-07-11 06:42:23,405] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 5.486 seconds
[2022-07-11 06:42:53,881] {processor.py:163} INFO - Started process (PID=703) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:42:53,884] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:42:53,885] {logging_mixin.py:109} INFO - [2022-07-11 06:42:53,884] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:42:54,610] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_operator_dag']) retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:42:54,624] {logging_mixin.py:109} INFO - [2022-07-11 06:42:54,623] {dag.py:2398} INFO - Sync 1 DAGs
[2022-07-11 06:42:54,652] {logging_mixin.py:109} INFO - [2022-07-11 06:42:54,651] {dag.py:2937} INFO - Setting next_dagrun for postgres_operator_dag to None
[2022-07-11 06:42:54,668] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.799 seconds
[2022-07-11 06:43:25,123] {processor.py:163} INFO - Started process (PID=728) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:43:25,124] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:43:25,125] {logging_mixin.py:109} INFO - [2022-07-11 06:43:25,125] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:43:25,896] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_operator_dag']) retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:43:25,927] {logging_mixin.py:109} INFO - [2022-07-11 06:43:25,925] {dag.py:2398} INFO - Sync 1 DAGs
[2022-07-11 06:43:25,976] {logging_mixin.py:109} INFO - [2022-07-11 06:43:25,976] {dag.py:2937} INFO - Setting next_dagrun for postgres_operator_dag to None
[2022-07-11 06:43:25,995] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 0.881 seconds
[2022-07-11 06:43:56,513] {processor.py:163} INFO - Started process (PID=759) to work on /opt/airflow/dags/example_postgres.py
[2022-07-11 06:43:56,529] {processor.py:642} INFO - Processing file /opt/airflow/dags/example_postgres.py for tasks to queue
[2022-07-11 06:43:56,531] {logging_mixin.py:109} INFO - [2022-07-11 06:43:56,531] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:43:58,353] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_operator_dag']) retrieved from /opt/airflow/dags/example_postgres.py
[2022-07-11 06:43:58,439] {logging_mixin.py:109} INFO - [2022-07-11 06:43:58,437] {dag.py:2398} INFO - Sync 1 DAGs
[2022-07-11 06:43:58,549] {logging_mixin.py:109} INFO - [2022-07-11 06:43:58,549] {dag.py:2937} INFO - Setting next_dagrun for postgres_operator_dag to None
[2022-07-11 06:43:58,614] {processor.py:171} INFO - Processing /opt/airflow/dags/example_postgres.py took 2.130 seconds
