[2022-07-05 05:30:51,377] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 05:30:51,433] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 05:30:51,433] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:30:51,433] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:30:51,433] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:30:51,499] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 01:00:00+00:00
[2022-07-05 05:30:51,527] {standard_task_runner.py:52} INFO - Started process 602 to run task
[2022-07-05 05:30:51,542] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T01:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpo2kno0wm', '--error-file', '/tmp/tmpkybagrzk']
[2022-07-05 05:30:51,543] {standard_task_runner.py:77} INFO - Job 135: Subtask kimuksung_test
[2022-07-05 05:30:51,757] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:30:52,065] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T01:00:00+00:00
[2022-07-05 05:30:52,066] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:30:52,067] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:30:52,136] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T010000, start_date=20220705T053051, end_date=20220705T053052
[2022-07-05 05:30:52,214] {standard_task_runner.py:92} ERROR - Failed to execute job 135 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:30:52,264] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:30:52,612] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:20:59,628] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 07:20:59,692] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 07:20:59,692] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:20:59,692] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:20:59,692] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:20:59,747] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 01:00:00+00:00
[2022-07-05 07:20:59,764] {standard_task_runner.py:52} INFO - Started process 535 to run task
[2022-07-05 07:20:59,789] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T01:00:00+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpuadu28is', '--error-file', '/tmp/tmp_qlfsr0d']
[2022-07-05 07:20:59,790] {standard_task_runner.py:77} INFO - Job 230: Subtask kimuksung_test
[2022-07-05 07:21:00,348] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:00,827] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T01:00:00+00:00
[2022-07-05 07:21:00,828] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:00,829] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:00,950] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T010000, start_date=20220705T072059, end_date=20220705T072100
[2022-07-05 07:21:00,996] {standard_task_runner.py:92} ERROR - Failed to execute job 230 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:01,027] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:01,332] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:10,225] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 07:25:10,325] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 07:25:10,325] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:10,326] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:10,326] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:10,434] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 01:00:00+00:00
[2022-07-05 07:25:10,452] {standard_task_runner.py:52} INFO - Started process 727 to run task
[2022-07-05 07:25:10,496] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T01:00:00+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp5p6k437r', '--error-file', '/tmp/tmpqdb294op']
[2022-07-05 07:25:10,499] {standard_task_runner.py:77} INFO - Job 261: Subtask kimuksung_test
[2022-07-05 07:25:11,042] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:11,406] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T01:00:00+00:00
[2022-07-05 07:25:11,435] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:11,436] {test.py:22} INFO - pubg
[2022-07-05 07:25:11,436] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:11,822] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T010000, start_date=20220705T072510, end_date=20220705T072511
[2022-07-05 07:25:12,025] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:12,274] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:27,040] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 08:05:27,118] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 08:05:27,118] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:27,118] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:27,119] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:27,209] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 01:00:00+00:00
[2022-07-05 08:05:27,217] {standard_task_runner.py:52} INFO - Started process 2062 to run task
[2022-07-05 08:05:27,237] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T01:00:00+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpfs8xiww9', '--error-file', '/tmp/tmpr2qdzugx']
[2022-07-05 08:05:27,238] {standard_task_runner.py:77} INFO - Job 293: Subtask kimuksung_test
[2022-07-05 08:05:27,461] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:27,870] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T01:00:00+00:00
[2022-07-05 08:05:27,872] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:27,872] {test.py:22} INFO - pubg
[2022-07-05 08:05:27,873] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:27,969] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T010000, start_date=20220705T080527, end_date=20220705T080527
[2022-07-05 08:05:28,066] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:05:28,272] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:10:41,809] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 08:10:41,897] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [queued]>
[2022-07-05 08:10:41,897] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:41,898] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:10:41,898] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:10:41,978] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 01:00:00+00:00
[2022-07-05 08:10:41,998] {standard_task_runner.py:52} INFO - Started process 2364 to run task
[2022-07-05 08:10:42,011] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T01:00:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpxfsyg3mo', '--error-file', '/tmp/tmp_n0o6i8j']
[2022-07-05 08:10:42,012] {standard_task_runner.py:77} INFO - Job 357: Subtask kimuksung_test
[2022-07-05 08:10:42,225] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T01:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:10:42,592] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T01:00:00+00:00
[2022-07-05 08:10:42,594] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:10:42,595] {test.py:22} INFO - pubg
[2022-07-05 08:10:42,595] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:10:42,899] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T010000, start_date=20220705T081041, end_date=20220705T081042
[2022-07-05 08:10:43,153] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:10:43,362] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
