[2022-07-05 05:34:20,237] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 05:34:20,388] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 05:34:20,388] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:34:20,389] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 05:34:20,389] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:34:20,714] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 14:00:00+00:00
[2022-07-05 05:34:20,752] {standard_task_runner.py:52} INFO - Started process 850 to run task
[2022-07-05 05:34:20,803] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T14:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpgq_gz7uf', '--error-file', '/tmp/tmpg_5hjun4']
[2022-07-05 05:34:20,804] {standard_task_runner.py:77} INFO - Job 213: Subtask kimuksung_test
[2022-07-05 05:34:21,273] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [running]> on host 5b96eb6af7d5
[2022-07-05 05:34:21,728] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T14:00:00+00:00
[2022-07-05 05:34:21,730] {logging_mixin.py:109} INFO - test function start
[2022-07-05 05:34:21,731] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:34:21,870] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T140000, start_date=20220705T053420, end_date=20220705T053421
[2022-07-05 05:34:21,980] {standard_task_runner.py:92} ERROR - Failed to execute job 213 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 05:34:22,054] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 05:34:22,392] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:21:18,940] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 07:21:18,995] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 07:21:18,995] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:18,995] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:21:18,995] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:21:19,065] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 14:00:00+00:00
[2022-07-05 07:21:19,089] {standard_task_runner.py:52} INFO - Started process 570 to run task
[2022-07-05 07:21:19,105] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T14:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp_434cep_', '--error-file', '/tmp/tmp9ym7fzy8']
[2022-07-05 07:21:19,109] {standard_task_runner.py:77} INFO - Job 243: Subtask kimuksung_test
[2022-07-05 07:21:19,320] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:21:19,526] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T14:00:00+00:00
[2022-07-05 07:21:19,529] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:21:19,541] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:19,625] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T140000, start_date=20220705T072118, end_date=20220705T072119
[2022-07-05 07:21:19,681] {standard_task_runner.py:92} ERROR - Failed to execute job 243 for task kimuksung_test
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 21, in test
    parameter=context["paramas"]["parameter1"]
KeyError: 'paramas'
[2022-07-05 07:21:19,729] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 07:21:19,797] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 07:25:31,487] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 07:25:31,646] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 07:25:31,646] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:31,646] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 07:25:31,646] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 07:25:31,891] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 14:00:00+00:00
[2022-07-05 07:25:31,959] {standard_task_runner.py:52} INFO - Started process 761 to run task
[2022-07-05 07:25:32,010] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T14:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpusdfbf0m', '--error-file', '/tmp/tmpxfcrl9de']
[2022-07-05 07:25:32,011] {standard_task_runner.py:77} INFO - Job 274: Subtask kimuksung_test
[2022-07-05 07:25:33,164] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 07:25:34,020] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T14:00:00+00:00
[2022-07-05 07:25:34,022] {logging_mixin.py:109} INFO - test function start
[2022-07-05 07:25:34,022] {test.py:22} INFO - pubg
[2022-07-05 07:25:34,023] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 07:25:34,185] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T140000, start_date=20220705T072531, end_date=20220705T072534
[2022-07-05 07:25:34,274] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 07:25:34,393] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:05:58,135] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 08:05:58,209] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 08:05:58,209] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:58,209] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:05:58,209] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:05:58,301] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 14:00:00+00:00
[2022-07-05 08:05:58,312] {standard_task_runner.py:52} INFO - Started process 2121 to run task
[2022-07-05 08:05:58,346] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T14:00:00+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmperc1aceq', '--error-file', '/tmp/tmp955zs54k']
[2022-07-05 08:05:58,347] {standard_task_runner.py:77} INFO - Job 318: Subtask kimuksung_test
[2022-07-05 08:05:58,917] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:05:59,396] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T14:00:00+00:00
[2022-07-05 08:05:59,397] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:05:59,397] {test.py:22} INFO - pubg
[2022-07-05 08:05:59,397] {python.py:175} INFO - Done. Returned value was: test function clear
[2022-07-05 08:05:59,513] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T140000, start_date=20220705T080558, end_date=20220705T080559
[2022-07-05 08:05:59,663] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:06:00,235] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-05 08:11:09,302] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 08:11:09,416] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [queued]>
[2022-07-05 08:11:09,417] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:09,417] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-07-05 08:11:09,417] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 08:11:09,552] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): kimuksung_test> on 2022-07-04 14:00:00+00:00
[2022-07-05 08:11:09,567] {standard_task_runner.py:52} INFO - Started process 2425 to run task
[2022-07-05 08:11:09,584] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'uk_dag_test_1', 'kimuksung_test', 'scheduled__2022-07-04T14:00:00+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpt6g5b77b', '--error-file', '/tmp/tmprhb_4mpd']
[2022-07-05 08:11:09,594] {standard_task_runner.py:77} INFO - Job 383: Subtask kimuksung_test
[2022-07-05 08:11:10,086] {logging_mixin.py:109} INFO - Running <TaskInstance: uk_dag_test_1.kimuksung_test scheduled__2022-07-04T14:00:00+00:00 [running]> on host 9514ca4c721b
[2022-07-05 08:11:10,537] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_dag_test_1
AIRFLOW_CTX_TASK_ID=kimuksung_test
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T14:00:00+00:00
[2022-07-05 08:11:10,539] {logging_mixin.py:109} INFO - test function start
[2022-07-05 08:11:10,545] {test.py:22} INFO - pubg
[2022-07-05 08:11:10,546] {python.py:175} INFO - Done. Returned value was: pubg
[2022-07-05 08:11:10,776] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=uk_dag_test_1, task_id=kimuksung_test, execution_date=20220704T140000, start_date=20220705T081109, end_date=20220705T081110
[2022-07-05 08:11:11,102] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-05 08:11:11,397] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
