[2022-07-20 05:40:41,225] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Upbit_api.insert_bitcoin scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 05:40:41,238] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Upbit_api.insert_bitcoin scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 05:40:41,238] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 05:40:41,238] {taskinstance.py:1244} INFO - Starting attempt 1 of 6
[2022-07-20 05:40:41,238] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 05:40:41,255] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): insert_bitcoin> on 2022-07-19 00:00:00+00:00
[2022-07-20 05:40:41,263] {standard_task_runner.py:52} INFO - Started process 553 to run task
[2022-07-20 05:40:41,269] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Upbit_api', 'insert_bitcoin', 'scheduled__2022-07-19T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/Upbit_Api.py', '--cfg-path', '/tmp/tmp9h7lqyv3', '--error-file', '/tmp/tmp532xc05d']
[2022-07-20 05:40:41,270] {standard_task_runner.py:77} INFO - Job 91: Subtask insert_bitcoin
[2022-07-20 05:40:41,345] {logging_mixin.py:109} INFO - Running <TaskInstance: Upbit_api.insert_bitcoin scheduled__2022-07-19T00:00:00+00:00 [running]> on host 0741836b2d3b
[2022-07-20 05:40:41,397] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'market'
[2022-07-20 05:40:41,412] {taskinstance.py:1282} INFO - Marking task as UP_FOR_RETRY. dag_id=Upbit_api, task_id=insert_bitcoin, execution_date=20220719T000000, start_date=20220720T054041, end_date=20220720T054041
[2022-07-20 05:40:41,430] {standard_task_runner.py:92} ERROR - Failed to execute job 91 for task insert_bitcoin
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'market'
[2022-07-20 05:40:41,481] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-20 05:40:41,517] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
